apiVersion: v1
kind: LimitRange
metadata:
  name: store-limits
spec:
  limits:
    - default:
        cpu: "500m"
        memory: 256Mi
      defaultRequest:
        cpu: "100m"
        memory: 128Mi
      type: Container
